### ISSUE TITLE
No module named 'dcn_op_v2'

### ISSUE THREAD

**Issue by Bru-Souza** [SsisyphusTao/Object-Detection-Knowledge-Distillation#12]
Dear @SsisyphusTao , thanks for starting this distillation approach with yolo v5.

I'm trying to run this on my computer, but I'm got this error: ModuleNotFoundError: No module named 'dcn_op_v2'.

I search on your others repositories, and I found the "Plugins for Pytorch & TensorRT". I've tried to install that, but I got another error: RuntimeError: Error compiling objects for extension. 

Do you know how can I fix that?

Best regards,

**Comment by SsisyphusTao** [comment]
I am not sure if it caused by pytorch version.. I once tried pytorch 1.8 and it didn't work, and I returned to pytorch 1.7, it's ok.. I hope this can help you.
